<?php
/**
 * @category   MageUC
 * @package    Developer
 * @author     Nicolas Bastien
 */
?>
<div id="mageuc-developer-bar-log" class="mageuc_developer_bar_panel" style="display: none;">
    <div class="mageuc_developer_bar_panel_content">
        <h2>Mage::log</h2>
        <div class="mageuc_developer_bar_panel_block">
            <table>
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>Level</th>
                        <th>Name</th>
                        <th>File</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getData() as $key => $log) : ?>
                        <tr>
                            <td><?php echo $key; ?></td>
                            <td><?php echo $log['level']; ?></td>
                            <td><?php echo $log['message']; ?></td>
                            <td><?php echo $log['file']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>