<?php
/**
 * Default page
 *
 * @category	MyApp
 * @package     MyApp_MyModule
 * @author      Nicolas Bastien
 */
?>


<h1>MyApp_MyModule</h1>
<p>
    This is a simple page to illustrate Custom magento template structure.
</p>
<p>
    If you want more information visit <br/>
    <a href="http://nicolas-bastien.com/en/magento/custom-template-structure">http://nicolas-bastien.com/en/magento/custom-template-structure</a>
</p>